export const solutionList = {
  peertube: "pt",
  funkwhale: "fw",
  taiga: "tg",
  discourse: "dc",
  owncloud: "oc",
  mattermost: "mm",
  tfhubValidator: "tfvalidator",
  casperlabs: "cl",
  presearch: "ps",
  caprover: "cp",
  kubernetes: "k8s",
  machines: "vm",
  nodepilot: "np",
  fullvm: "fvm",
};
